# Generated by Django 2.2.16 on 2020-09-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='类别ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='类别名')),
            ],
            options={
                'verbose_name_plural': '类别表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='菜单名')),
                ('img_path', models.CharField(default='', max_length=100, verbose_name='图片路径')),
                ('img_file', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Category')),
            ],
            options={
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=50, verbose_name='用户ID')),
                ('is_paid', models.BooleanField(verbose_name='是否已支付')),
                ('address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('order_time', models.DateTimeField(verbose_name='下单时间')),
                ('pay_time', models.DateTimeField(verbose_name='支付时间')),
                ('menus', models.ManyToManyField(to='hello.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False, verbose_name='购物车ID')),
                ('open_id', models.CharField(max_length=50, verbose_name='')),
                ('menu', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.Menu')),
            ],
        ),
    ]
